const LABELS = [
    'airplane',
    'alarm clock',
    'angel',
    'ant',
    'apple',
    'axe',
    'baseball',
    'bat',
    'beard',
    'bee',
    'bicycle',
    'bird',
    'birthday cake',
    'boomerang',
    'broccoli',
    'broom',
    'bus',
    'butterfly',
    'cactus',
    'calculator',
    'camel',
    'camera',
    'candle',
    'car',
    'carrot',
    'castle',
    'cat',
    'chair',
    'church',
    'clock',
    'cloud',
    'coffee cup',
    'crab',
    'crown',
    'diamond',
    'dog',
    'duck',
    'dumbbell',
    'elephant',
    'envelope',
    'eye',
    'eyeglasses',
    'feather',
    'fence',
    'fire hydrant',
    'fish',
    'flamingo',
    'flower',
    'flying saucer',
    'foot',
    'giraffe',
    'golf club',
    'grapes',
    'guitar',
    'hamburger',
    'hammer',
    'harp',
    'hat',
    'helicopter',
    'hot air balloon',
    'hourglass',
    'house',
    'ice cream',
    'key',
    'ladder',
    'leaf',
    'light bulb',
    'lightning',
    'lipstick',
    'lollipop',
    'mailbox',
    'megaphone',
    'mountain',
    'nose',
    'octopus',
    'owl',
    'paint can',
    'paintbrush',
    'palm tree',
    'pants',
    'paper clip',
    'parachute',
    'pineapple',
    'postcard',
    'power outlet',
    'rainbow',
    'rake',
    'rollerskates',
    'sailboat',
    'saw',
    'school bus',
    'scissors',
    'screwdriver',
    'shoe',
    'shorts',
    'skateboard',
    'skyscraper',
    'snail',
    'snowman',
    'spider',
    'spoon',
    'stairs',
    'star',
    'suitcase',
    'sun',
    'swing set',
    'syringe',
    't-shirt',
    'table',
    'television',
    'tennis racquet',
    'tent',
    'the eiffel tower',
    'the mona lisa',
    'toaster',
    'tooth',
    'toothbrush',
    'tornado',
    'traffic light',
    'train',
    'tree',
    'trombone',
    'trumpet',
    'umbrella',
    'washing machine',
    'whale',
    'windmill',
    'wine bottle',
    'wine glass',
    'wristwatch'    
];

var LABELS_LOOKUP = {};

for (let i = 0; i < LABELS.length; i++) {
    LABELS_LOOKUP[LABELS[i]] = i;
}